FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    pkg-config \
    libboost-all-dev \
    inotify-tools

RUN apt-get update && apt-get install -y libpqxx-dev libpq-dev
WORKDIR /app

COPY CMakeLists.txt ./

COPY entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh


EXPOSE 8080

RUN apt-get install -y entr

ENTRYPOINT ["/app/entrypoint.sh"]